# -*- coding: utf-8 -*-
"""txt to csv .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qyIAXXy_VNDg-CJIUK2dLotBpJiWsJs_
"""

import csv

# Read from davis.txt and write to davis.csv
with open('Davis.txt', 'r') as infile, open('Davis.csv', 'w', newline='') as outfile:
    writer = csv.writer(outfile)
    writer.writerow(['drug_id', 'protein_id', 'smiles', 'sequence', 'label'])  # CSV header

    for line in infile:
        parts = line.strip().split()
        if len(parts) >= 5:
            drug_id = parts[0]
            protein_id = parts[1]
            smiles = parts[2]
            sequence = parts[3]
            label = parts[4]
            writer.writerow([drug_id, protein_id, smiles, sequence, label])